# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Currency
version:      0.38
version_from: Currency.pm
installdirs:  site
requires:
    Math::BigFloat:                1.27
    Test::More:                    0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
